# -*- coding: utf-8 -*-
"""Python_3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b46l3c_qKNgxOZLxdvVLPiVw2JIsO6fx

Python Lists
"""

a=['Raj','Raja','Rajaram','RajaRaja']
print(type(a))
print(a)

"""Pyhton Tuples"""

b=('Raj','Raja','Rajaram','RajaRaja')
print(type(b))
print(b)